### ISSUE TITLE
[BUG] [iOS] stutter in pageview

### ISSUE THREAD

**Issue by cahix** [juliuscanute/qr_code_scanner#201]
On iOS there is a strong stuttering when switching from the qr-scanner to another widget in a PageView. Switching to the qr-scanner is fine.

Flutter (Channel beta, 1.25.0-8.1.pre, on Microsoft Windows [Version 10.0.18363.1256], locale en-US

 - Device: iPhone7
 - OS: 13.7

**Comment by smofe** [comment]
Have you tried running your project in --release or --profile mode? I've had performance issues on android that were only present when running the app in debug mode.

**Comment by cahix** [comment]
@smofe yes i did. 
it seems like the closing of the camera causes the stutter on my iphone

**Comment by cahix** [comment]
fixed by calling "controller.pauseCamera()" before disposing

**Comment by cahix** [comment]
issue is back on versions above 0.1.0

**Comment by clragon** [comment]
I'm also having this issue. 
The stuttering in fact will cancel swiping in my pageview, which is a big issue.

**Comment by juliansteenbakker** [comment]
With version 0.3.2 disposing is done differently. Can you please try again?

**Comment by cahix** [comment]
i still have the same problem

**Comment by cahix** [comment]
also, i can see the camera preview in the background of my other widgets in the page-view just before the scanner disposes.

**Comment by cahix** [comment]
@juliansteenbakker any chance you have a look at this again? 
I am still using version 0.1.0 because it does not cause stuttering when the qr-scanner is disposed in the background.

Best regards

**Comment by seth35us** [comment]
@cahix I tried your fix, but got the following error after switching tabs multiple times: Scan rect cannot be set when not (yet) scanning. You may want to set it within didStartScanningBlock. I have the scanner set in a bottomNavigationBar. I think this is related to bug #283.

**Comment by juliansteenbakker** [comment]
Sorry for the late response but i haven't had the time to look at this. As a matter of fact, i'm almost ready to publish the first release with MLKit support. In my tests this works like so much better than the current frameworks used. So i'd advise you to try that out when i'm releasing it.

> Is it possible that the code below is causing the crash? We need to ensure that scanning has started before setting the dimensions.

I do think that would cause an issue. I have stumbled on multiple errors regarding `'NSInternalInconsistencyException', reason: 'Scan rect cannot be set when not (yet) scanning. You may want to set it within didStartScanningBlock.' `
Ill try to add a check to see if it's scanning before setting the rect.

**Comment by cahix** [comment]
Will you be releasing it as a version in this package or will it be a completely new one? Just making sure I do not miss it.

**Comment by juliansteenbakker** [comment]
> Will you be releasing it as a version in this package or will it be a completely new one? Just making sure I do not miss it.

I just released the first alpha version. It's integrated in this package. Keep in mind the class names can change until it reaches beta.

**Comment by davemg3** [comment]
Hi, error still going
With the QRView in a tab, by switching 3 or 4 times, i get a crash with : 
@juliansteenbakker , do you mean this is an usual bug you got in this library with no clues how to fix it soon?
thks

```

*** Assertion failure in -[MTBBarcodeScanner setScanRect:], MTBBarcodeScanner.m:973
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Scan rect cannot be set when not (yet) scanning. You may want to set it within didStartScanningBlock.'
*** First throw call stack:
(0x199402754 0x1adec97a8 0x1993043f8 0x19a6d8714 0x103c760f4 0x10659c000 0x10659c250 0x103c721c4 0x198feda84 0x198fef81c 0x198ffdc70 0x19937c398 0x199376270 0x199375360 0x1b09b3734 0x19bdf0584 0x19bdf5df4 0x10005c24c 0x199031cf8)
libc++abi: terminating with uncaught exception of type NSException
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001c7633334 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1c7633334 <+8>:  b.lo   0x1c7633354               ; <+40>
    0x1c7633338 <+12>: pacibsp 
    0x1c763333c <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1c7633340 <+20>: mov    x29, sp
Target 0: (Runner) stopped.
```
